using Zeeq.Core.Models;

namespace Zeeq.Platform.CodeReviews;

/// <summary>
/// Baseline file exclusions applied to every repository's review scope, regardless of
/// that repository's own <see cref="CodeReviewFileFilter"/> configuration.
/// </summary>
/// <remarks>
/// Mirrors how <c>IngestFileFilter</c> hardcodes a Markdown-only narrowing rule ahead of
/// the configured filter — this is the code-review equivalent: lockfiles, build output,
/// vendored dependencies, generated code, and editor/OS noise are never useful to a
/// reviewer agent and are excluded unconditionally, with zero per-repo setup required.
/// <para>
/// Unlike a repository's own <see cref="CodeReviewFileFilter.ExcludedFiles"/> (which
/// always wins over that repository's includes), a baseline exclusion here can be
/// overridden by an explicit match in the repository's own
/// <see cref="CodeReviewFileFilter.IncludedFiles"/> allowlist — see
/// <see cref="CodeReviewFileFilterEvaluator"/> for the precedence order. A repo that
/// deliberately wants lockfile diffs reviewed (e.g. for supply-chain awareness) adds an
/// include rule for that pattern rather than needing this list changed.
/// </para>
/// <para>
/// Patterns use the <see cref="CodeReviewFileNameMatchType.Glob"/> dialect
/// (<c>Microsoft.Extensions.FileSystemGlobbing</c>, matched case-insensitively) via
/// <see cref="CodeReviewFilePatternMatcher"/>.
/// </para>
/// </remarks>
internal static class CodeReviewDefaultFileExclusions
{
    /// <summary>
    /// Baseline glob patterns excluded from every repository's review scope.
    /// </summary>
    public static IReadOnlyList<CodeReviewFileMatchCriteria> Criteria { get; } =
        [
            // --- Lockfiles: generated by the package manager, never hand-edited ---
            // ".lock" covers yarn.lock, Gemfile.lock, poetry.lock, Pipfile.lock,
            // uv.lock, Cargo.lock, pubspec.lock, and composer.lock in one pattern.
            // The remaining ecosystems use a different extension for their lockfile
            // and need their own entry.
            Glob("**/*.lock"),
            Glob("**/package-lock.json"), // npm
            Glob("**/npm-shrinkwrap.json"), // npm (legacy)
            Glob("**/pnpm-lock.yaml"), // pnpm
            Glob("**/packages.lock.json"), // NuGet (C#/.NET)
            Glob("**/go.sum"), // Go (go.mod is hand-edited, kept in scope)
            Glob("**/gradle.lockfile"), // Gradle (Java/Kotlin)
            // --- Build output / compiled artifacts ---
            Glob("**/bin/**"), // C#/.NET
            Glob("**/obj/**"), // C#/.NET
            Glob("**/*.dll"),
            Glob("**/*.pdb"),
            Glob("**/target/**"), // Java (Maven), Rust
            Glob("**/build/**"), // Gradle, JS/TS, Dart/Flutter
            Glob("**/*.class"), // Java
            Glob("**/*.jar"), // Java
            Glob("**/__pycache__/**"), // Python
            Glob("**/*.pyc"), // Python
            Glob("**/*.pyo"), // Python
            Glob("**/*.egg-info/**"), // Python
            Glob("**/.eggs/**"), // Python
            Glob("**/dist/**"), // JS/TS, Python
            Glob("**/.next/**"), // JS/TS (Next.js)
            Glob("**/.nuxt/**"), // JS/TS (Nuxt)
            Glob("**/.output/**"), // JS/TS (Nuxt/Nitro)
            Glob("**/*.min.js"), // JS/TS
            Glob("**/*.min.css"), // JS/TS
            Glob("**/*.map"), // JS/TS sourcemaps
            Glob("**/.dart_tool/**"), // Dart/Flutter
            // --- Dependency / vendor directories ---
            Glob("**/node_modules/**"), // JS/TS/Node
            Glob("**/vendor/**"), // Go, PHP, Ruby (bundle path alias)
            Glob("**/.venv/**"), // Python
            Glob("**/venv/**"), // Python
            Glob("**/site-packages/**"), // Python
            Glob("**/.gradle/**"), // Java/Kotlin
            Glob("**/.m2/**"), // Java (Maven)
            Glob("**/.pub-cache/**"), // Dart/Flutter
            Glob("**/Pods/**"), // CocoaPods (Dart/Flutter iOS interop)
            // --- Generated code: source-generator or codegen output, never hand-edited ---
            Glob("**/*.g.cs"), // C# source generators
            Glob("**/*.g.i.cs"), // C# source generators
            Glob("**/*.designer.cs"), // C# designer files, incl. EF Core migration snapshots
            Glob("**/*_pb2.py"), // Python protobuf
            Glob("**/*.pb.go"), // Go protobuf
            Glob("**/*.pb.cs"), // C# protobuf
            Glob("**/*.g.dart"), // Dart codegen (build_runner)
            Glob("**/*.freezed.dart"), // Dart codegen (freezed)
            // --- IDE / editor / OS noise ---
            Glob("**/.vs/**"),
            Glob("**/.vscode/**"),
            Glob("**/.idea/**"),
            Glob("**/*.suo"),
            Glob("**/*.user"),
            Glob("**/.DS_Store"),
            Glob("**/Thumbs.db"),
            // --- Version control internals ---
            Glob("**/.git/**"),
            // --- Binary / media: not reviewable as a text diff ---
            Glob("**/*.png"),
            Glob("**/*.jpg"),
            Glob("**/*.jpeg"),
            Glob("**/*.gif"),
            Glob("**/*.ico"),
            Glob("**/*.woff"),
            Glob("**/*.woff2"),
            Glob("**/*.ttf"),
            Glob("**/*.pdf"),
            Glob("**/*.zip"),
        ];

    private static CodeReviewFileMatchCriteria Glob(string pattern) =>
        new() { MatchType = CodeReviewFileNameMatchType.Glob, Pattern = pattern };
}
