using System.Collections.Frozen;

namespace Zeeq.Core.Identity;

/// <summary>
/// Curated public/free mailbox domain exclusion list for same-domain onboarding.
/// </summary>
/// <remarks>
/// Sources reviewed:
/// - Gong public email domains exclusion list, updated 2026-02-12.
/// - Kikobeats/free-email-domains open-source list.
/// - Practical top email domains seed list by ef1500.
/// - Public Suffix List for registrable-domain context only.
///
/// This is intentionally a curated high-confidence list instead of a full
/// disposable-domain import. Same-domain onboarding should prevent obvious
/// public mailbox providers without rejecting long-tail legitimate company
/// domains that happen to appear on aggressive free/disposable lists.
/// </remarks>
public static class PublicEmailDomainCatalog
{
    private static readonly FrozenSet<string> Domains = new[]
        {
            "126.com",
            "139.com",
            "163.com",
            "188.com",
            "189.cn",
            "21cn.com",
            "263.net",
            "alice.it",
            "aliceadsl.fr",
            "aliyun.com",
            "aim.com",
            "aol.com",
            "aol.co.uk",
            "aol.fr",
            "aol.it",
            "arcor.de",
            "arnet.com.ar",
            "att.net",
            "bell.net",
            "bellsouth.net",
            "bigpond.com",
            "bigpond.com.au",
            "bigpond.net.au",
            "bk.ru",
            "bluewin.ch",
            "blueyonder.co.uk",
            "bol.com.br",
            "bt.com",
            "btinternet.com",
            "centrum.cz",
            "charter.net",
            "chello.nl",
            "club-internet.fr",
            "comcast.net",
            "cox.net",
            "daum.net",
            "earthlink.net",
            "email.com",
            "email.it",
            "facebook.com",
            "fastmail.com",
            "fastmail.fm",
            "fibertel.com.ar",
            "foxmail.com",
            "free.fr",
            "freenet.de",
            "games.com",
            "globo.com",
            "globomail.com",
            "gmail.com",
            "gmx.at",
            "gmx.ch",
            "gmx.com",
            "gmx.de",
            "gmx.fr",
            "gmx.net",
            "googlemail.com",
            "hanmail.net",
            "hetnet.nl",
            "home.nl",
            "hotmail.be",
            "hotmail.ca",
            "hotmail.co.uk",
            "hotmail.com",
            "hotmail.com.ar",
            "hotmail.com.br",
            "hotmail.com.mx",
            "hotmail.de",
            "hotmail.es",
            "hotmail.fr",
            "hotmail.it",
            "hush.com",
            "hushmail.com",
            "icloud.com",
            "ig.com.br",
            "iname.com",
            "inbox.com",
            "inbox.ru",
            "juno.com",
            "keemail.me",
            "laposte.net",
            "lavabit.com",
            "libero.it",
            "list.ru",
            "live.be",
            "live.ca",
            "live.co.uk",
            "live.com",
            "live.com.ar",
            "live.com.au",
            "live.com.mx",
            "live.de",
            "live.fr",
            "live.it",
            "live.nl",
            "love.com",
            "mac.com",
            "mail.com",
            "mail.ru",
            "me.com",
            "msn.com",
            "nate.com",
            "naver.com",
            "neuf.fr",
            "ntlworld.com",
            "oi.com.br",
            "online.de",
            "optonline.net",
            "optusnet.com.au",
            "orange.fr",
            "orange.net",
            "outlook.com",
            "outlook.com.br",
            "planet.nl",
            "pobox.com",
            "poste.it",
            "prodigy.net.mx",
            "proton.me",
            "protonmail.ch",
            "protonmail.com",
            "qq.com",
            "r7.com",
            "rambler.ru",
            "rediffmail.com",
            "rocketmail.com",
            "rogers.com",
            "safe-mail.net",
            "sbcglobal.net",
            "sfr.fr",
            "shaw.ca",
            "sina.cn",
            "sina.com",
            "sky.com",
            "skynet.be",
            "speedy.com.ar",
            "sympatico.ca",
            "t-online.de",
            "talktalk.co.uk",
            "telenet.be",
            "teletu.it",
            "terra.com.br",
            "tin.it",
            "tiscali.co.uk",
            "tiscali.it",
            "tuta.io",
            "tutamail.com",
            "tutanota.com",
            "tutanota.de",
            "tvcablenet.be",
            "uol.com.br",
            "verizon.net",
            "virgilio.it",
            "voila.fr",
            "wanadoo.fr",
            "web.de",
            "windowslive.com",
            "windstream.net",
            "wp.pl",
            "ya.ru",
            "yahoo.ca",
            "yahoo.cn",
            "yahoo.co.id",
            "yahoo.co.in",
            "yahoo.co.jp",
            "yahoo.co.kr",
            "yahoo.co.nz",
            "yahoo.co.uk",
            "yahoo.com",
            "yahoo.com.ar",
            "yahoo.com.au",
            "yahoo.com.br",
            "yahoo.com.hk",
            "yahoo.com.mx",
            "yahoo.com.ph",
            "yahoo.com.sg",
            "yahoo.de",
            "yahoo.es",
            "yahoo.fr",
            "yahoo.in",
            "yahoo.it",
            "yandex.com",
            "yandex.ru",
            "yeah.net",
            "ymail.com",
            "zoho.com",
            "zonnet.nl",
        }.ToFrozenSet(StringComparer.OrdinalIgnoreCase);

    /// <summary>
    /// Returns true when the normalized domain is a known public/free mailbox provider.
    /// </summary>
    public static bool IsPublicEmailDomain(string? domain)
    {
        var normalized = EmailDomainNormalizer.FromDomain(domain);

        return normalized is not null && Domains.Contains(normalized);
    }
}
