-- Reuse requires dedicated, initially empty Zeeq schemas and a dedicated zeeq_owner LOGIN.
-- Remove only installation SQL; preserve externally prepared extension/role infrastructure.
BEGIN;
DO $$
DECLARE item record;
BEGIN
  IF current_user <> 'zeeq_owner' THEN
    RAISE EXCEPTION 'Cleanup requires the persistent zeeq_owner identity';
  END IF;
  IF EXISTS (SELECT FROM pg_namespace WHERE nspname IN ('zeeq','messaging','cache') AND nspowner <> current_user::regrole) THEN
    RAISE EXCEPTION 'Refusing cleanup: application schema ownership changed';
  END IF;
  IF EXISTS (SELECT FROM partman.part_config
    WHERE parent_table LIKE 'zeeq.%'
      AND (SELECT relowner FROM pg_class WHERE oid=to_regclass(parent_table)) IS DISTINCT FROM current_user::regrole) THEN
    RAISE EXCEPTION 'Refusing cleanup: partition parent ownership changed';
  END IF;
  IF EXISTS (SELECT FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace
    WHERE n.nspname IN ('zeeq','messaging','cache') AND c.relowner <> current_user::regrole) THEN
    RAISE EXCEPTION 'Refusing cleanup: application relation ownership changed';
  END IF;
  IF EXISTS (SELECT FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace
    WHERE n.nspname IN ('zeeq','messaging','cache') AND p.proowner <> current_user::regrole) THEN
    RAISE EXCEPTION 'Refusing cleanup: application routine ownership changed';
  END IF;
  IF EXISTS (SELECT FROM pg_type t JOIN pg_namespace n ON n.oid=t.typnamespace
    WHERE n.nspname IN ('zeeq','messaging','cache') AND t.typtype IN ('e','d') AND t.typowner <> current_user::regrole) THEN
    RAISE EXCEPTION 'Refusing cleanup: application type ownership changed';
  END IF;
  FOR item IN SELECT jobid FROM cron.job WHERE username = current_user AND jobname IN ('code-review-github-webhook-delivery-claim-retention','zeeq_pg_partman_maintenance','zeeq_prune_carts','zeeq_prune_cron_history') LOOP
    PERFORM cron.unschedule(item.jobid);
  END LOOP;
  FOR item IN SELECT DISTINCT template_table FROM partman.part_config WHERE parent_table LIKE 'zeeq.%' AND template_table IS NOT NULL LOOP
    -- pg_partman templates are generated by this installation owner, never shared extension tables.
    IF to_regclass(item.template_table) IS NULL THEN
      RAISE EXCEPTION 'Refusing cleanup: partition template is missing';
    END IF;
    IF (SELECT relowner FROM pg_class WHERE oid=to_regclass(item.template_table)) <> current_user::regrole THEN
      RAISE EXCEPTION 'Refusing cleanup: partition template ownership changed';
    END IF;
    EXECUTE format('DROP TABLE IF EXISTS %s', item.template_table::regclass);
  END LOOP;
  DELETE FROM partman.part_config WHERE parent_table LIKE 'zeeq.%';
END $$;
-- Keep externally prepared schemas; the owner has no database CREATE privilege to recreate them.
DO $$
DECLARE item record; dropped boolean;
BEGIN
  IF EXISTS (SELECT FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace
    WHERE n.nspname IN ('zeeq','messaging','cache') AND c.relowner <> current_user::regrole) THEN
    RAISE EXCEPTION 'Refusing cleanup: application relation ownership changed';
  END IF;
  FOR item IN SELECT n.nspname,c.relname,k.conname FROM pg_constraint k JOIN pg_class c ON c.oid=k.conrelid JOIN pg_namespace n ON n.oid=c.relnamespace
    WHERE k.contype='f' AND n.nspname IN ('zeeq','messaging','cache') LOOP
    EXECUTE format('ALTER TABLE %I.%I DROP CONSTRAINT IF EXISTS %I',item.nspname,item.relname,item.conname);
  END LOOP;
  -- Retry installation objects leaves-first. RESTRICT preserves every external dependency.
  -- NOTE: Dropping tables removes their indexes and constraints automatically; indexes are not independent objects.
  LOOP
    dropped := false;
    FOR item IN
      SELECT format('DROP %s IF EXISTS %I.%I',CASE c.relkind WHEN 'v' THEN 'VIEW' WHEN 'm' THEN 'MATERIALIZED VIEW' WHEN 'S' THEN 'SEQUENCE' WHEN 'f' THEN 'FOREIGN TABLE' ELSE 'TABLE' END,n.nspname,c.relname) AS ddl
      FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace
      WHERE n.nspname IN ('zeeq','messaging','cache') AND c.relkind IN ('r','p','f','v','m','S')
      UNION ALL
      SELECT format('DROP %s IF EXISTS %s',CASE p.prokind WHEN 'a' THEN 'AGGREGATE' ELSE 'ROUTINE' END,p.oid::regprocedure)
      FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname IN ('zeeq','messaging','cache')
      UNION ALL
      SELECT format('DROP %s IF EXISTS %I.%I',CASE t.typtype WHEN 'd' THEN 'DOMAIN' ELSE 'TYPE' END,n.nspname,t.typname)
      FROM pg_type t JOIN pg_namespace n ON n.oid=t.typnamespace WHERE n.nspname IN ('zeeq','messaging','cache') AND t.typtype IN ('e','d')
    LOOP
      BEGIN
        EXECUTE item.ddl;
        dropped := true;
      EXCEPTION WHEN dependent_objects_still_exist THEN
        NULL;
      END;
    END LOOP;
    EXIT WHEN NOT EXISTS (SELECT FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace
      WHERE n.nspname IN ('zeeq','messaging','cache') AND c.relkind IN ('r','p','f','v','m','S'))
      AND NOT EXISTS (SELECT FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname IN ('zeeq','messaging','cache'))
      AND NOT EXISTS (SELECT FROM pg_type t JOIN pg_namespace n ON n.oid=t.typnamespace WHERE n.nspname IN ('zeeq','messaging','cache') AND t.typtype IN ('e','d'));
    IF NOT dropped THEN RAISE EXCEPTION 'Refusing cleanup: installation objects have external dependencies'; END IF;
  END LOOP;
END $$;
COMMIT;
