// <auto-generated />
using System;
using Zeeq.Data.Postgres;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Zeeq.Data.Postgres.Migrations.Migrations
{
    [DbContext(typeof(PostgresDbContext))]
    [Migration("20260621234152_AddGitHubCodeReviewStorage")]
    partial class AddGitHubCodeReviewStorage
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("zeeq")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "fuzzystrmatch");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pg_cron");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pg_partman");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pg_trgm");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Zeeq.Core.Models.ActiveCodeReviewLock", b =>
                {
                    b.Property<string>("OrganizationId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("organization_id");

                    b.Property<string>("PullRequestRecordId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("pull_request_record_id");

                    b.Property<DateTimeOffset>("AcquiredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("acquired_at_utc");

                    b.Property<DateTimeOffset>("CodeReviewCreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("code_review_created_at_utc");

                    b.Property<string>("CodeReviewRecordId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("code_review_record_id");

                    b.Property<DateTimeOffset>("PullRequestCreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("pull_request_created_at_utc");

                    b.Property<string>("RepositoryId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("repository_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<string>("TeamId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("team_id");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("OrganizationId", "PullRequestRecordId")
                        .HasName("pk_code_review_active_locks");

                    b.HasIndex("CodeReviewRecordId")
                        .IsUnique()
                        .HasDatabaseName("ix_code_review_active_locks_code_review_record_id");

                    b.HasIndex("OrganizationId", "TeamId", "UpdatedAtUtc")
                        .HasDatabaseName("ix_code_review_active_locks_organization_id_team_id_updated_at");

                    b.ToTable("code_review_active_locks", "zeeq");
                });

            modelBuilder.Entity("Zeeq.Core.Models.AuthTransientState", b =>
                {
                    b.Property<string>("Purpose")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("purpose");

                    b.Property<string>("Key")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("key");

                    b.Property<DateTimeOffset?>("ConsumedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("consumed_at_utc");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at_utc");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("payload_json");

                    b.HasKey("Purpose", "Key")
                        .HasName("pk_auth_transient_states");

                    b.HasIndex("Purpose", "ExpiresAtUtc", "ConsumedAtUtc")
                        .HasDatabaseName("ix_auth_transient_states_purpose_expires_at_utc_consumed_at_utc");

                    b.ToTable("auth_transient_states", "zeeq");
                });

            modelBuilder.Entity("Zeeq.Core.Models.ClientCredential", b =>
                {
                    b.Property<string>("ClientId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("client_id");

                    b.Property<string>("ClientSecret")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("client_secret");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<string>("OrganizationId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("organization_id");

                    b.Property<string>("OwnerProvider")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("owner_provider");

                    b.Property<string>("OwnerProviderSubject")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("owner_provider_subject");

                    b.Property<string>("OwnerUserId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("owner_user_id");

                    b.Property<DateTimeOffset?>("RevokedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at_utc");

                    b.Property<string>("SelectedPartitionIdsJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("selected_partition_ids_json");

                    b.Property<string>("TeamId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("team_id");

                    b.HasKey("ClientId")
                        .HasName("pk_auth_client_credentials");

                    b.HasIndex("OwnerUserId")
                        .HasDatabaseName("ix_auth_client_credentials_owner_user_id");

                    b.HasIndex("OrganizationId", "TeamId", "OwnerUserId")
                        .HasDatabaseName("ix_auth_client_credentials_organization_id_team_id_owner_user_");

                    b.ToTable("auth_client_credentials", "zeeq");
                });

            modelBuilder.Entity("Zeeq.Core.Models.CodeRepository", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("id");

                    b.Property<string>("ConfigurationJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("configuration_json");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTimeOffset?>("DisabledAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("disabled_at_utc");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("display_name");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled");

                    b.Property<string>("OrganizationId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("organization_id");

                    b.Property<string>("OwnerQualifiedName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("owner_qualified_name");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("provider");

                    b.Property<string>("TeamId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("team_id");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_code_review_repositories");

                    b.HasIndex("OrganizationId", "Provider", "OwnerQualifiedName")
                        .IsUnique()
                        .HasDatabaseName("ix_code_review_repositories_organization_id_provider_owner_qua")
                        .HasFilter("disabled_at_utc IS NULL");

                    b.HasIndex("OrganizationId", "TeamId", "DisabledAtUtc")
                        .HasDatabaseName("ix_code_review_repositories_organization_id_team_id_disabled_a");

                    b.HasIndex("Provider", "OwnerQualifiedName", "DisabledAtUtc")
                        .HasDatabaseName("ix_code_review_repositories_provider_owner_qualified_name_disa");

                    b.ToTable("code_review_repositories", "zeeq");
                });

            modelBuilder.Entity("Zeeq.Core.Models.CodeReviewRecord", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("AuthorLogin")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("author_login");

                    b.Property<string>("Branch")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("branch");

                    b.Property<int>("CommentFindings")
                        .HasColumnType("integer")
                        .HasColumnName("comment_findings");

                    b.Property<int>("CriticalFindings")
                        .HasColumnType("integer")
                        .HasColumnName("critical_findings");

                    b.Property<DateTimeOffset?>("DisabledAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("disabled_at_utc");

                    b.Property<string>("FailureMessage")
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)")
                        .HasColumnName("failure_message");

                    b.Property<string>("FindingsPayload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("findings_payload");

                    b.Property<string>("FindingsStorageUri")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("findings_storage_uri");

                    b.Property<int>("MajorFindings")
                        .HasColumnType("integer")
                        .HasColumnName("major_findings");

                    b.Property<int>("MinorFindings")
                        .HasColumnType("integer")
                        .HasColumnName("minor_findings");

                    b.Property<string>("OrganizationId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("organization_id");

                    b.Property<string>("OwnerQualifiedRepoName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("owner_qualified_repo_name");

                    b.Property<int>("PullRequestNumber")
                        .HasColumnType("integer")
                        .HasColumnName("pull_request_number");

                    b.Property<string>("PullRequestRecordId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("pull_request_record_id");

                    b.Property<int>("RemainingReviewBudget")
                        .HasColumnType("integer")
                        .HasColumnName("remaining_review_budget");

                    b.Property<string>("RepositoryId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("repository_id");

                    b.Property<string>("RequestOrigin")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("request_origin");

                    b.Property<string>("ReviewGroupId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("review_group_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<int>("SuggestionFindings")
                        .HasColumnType("integer")
                        .HasColumnName("suggestion_findings");

                    b.Property<string>("TeamId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("team_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id", "CreatedAtUtc")
                        .HasName("pk_code_review_records");

                    b.HasIndex("PullRequestRecordId", "Status")
                        .HasDatabaseName("ix_code_review_records_pull_request_record_id_status");

                    b.HasIndex("OrganizationId", "RequestOrigin", "CreatedAtUtc")
                        .HasDatabaseName("ix_code_review_records_organization_id_request_origin_created_");

                    b.HasIndex("OrganizationId", "TeamId", "CreatedAtUtc")
                        .HasDatabaseName("ix_code_review_records_organization_id_team_id_created_at_utc");

                    b.ToTable("code_review_records", "zeeq");
                });

            modelBuilder.Entity("Zeeq.Core.Models.DcrClientSetup", b =>
                {
                    b.Property<string>("ClientId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("client_id");

                    b.Property<DateTimeOffset?>("ClaimedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("claimed_at_utc");

                    b.Property<string>("ClaimedOwnerProvider")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("claimed_owner_provider");

                    b.Property<string>("ClaimedOwnerProviderSubject")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("claimed_owner_provider_subject");

                    b.Property<string>("ClaimedUserId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("claimed_user_id");

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("client_name");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at_utc");

                    b.Property<string>("OrganizationId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("organization_id");

                    b.Property<string>("RedirectUrisJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("redirect_uris_json");

                    b.Property<string>("RequestedScopes")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("requested_scopes");

                    b.Property<DateTimeOffset?>("RevokedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at_utc");

                    b.Property<string>("SelectedPartitionIdsJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("selected_partition_ids_json");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("status");

                    b.Property<string>("TeamId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("team_id");

                    b.HasKey("ClientId")
                        .HasName("pk_auth_dcr_client_setups");

                    b.HasIndex("ClaimedUserId")
                        .HasDatabaseName("ix_auth_dcr_client_setups_claimed_user_id");

                    b.HasIndex("Status", "ExpiresAtUtc")
                        .HasDatabaseName("ix_auth_dcr_client_setups_status_expires_at_utc");

                    b.HasIndex("OrganizationId", "TeamId", "ClaimedUserId")
                        .HasDatabaseName("ix_auth_dcr_client_setups_organization_id_team_id_claimed_user");

                    b.ToTable("auth_dcr_client_setups", "zeeq");
                });

            modelBuilder.Entity("Zeeq.Core.Models.ExternalUserIdentity", b =>
                {
                    b.Property<string>("Provider")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("provider");

                    b.Property<string>("ProviderSubject")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("provider_subject");

                    b.Property<DateTimeOffset?>("DisabledAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("disabled_at_utc");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailVerified")
                        .HasColumnType("boolean")
                        .HasColumnName("email_verified");

                    b.Property<DateTimeOffset>("FirstSeenAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_seen_at_utc");

                    b.Property<DateTimeOffset>("LastSeenAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at_utc");

                    b.Property<string>("PictureUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("picture_url");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("user_id");

                    b.HasKey("Provider", "ProviderSubject")
                        .HasName("pk_auth_user_identities");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_auth_user_identities_user_id");

                    b.ToTable("auth_user_identities", "zeeq");
                });

            modelBuilder.Entity("Zeeq.Core.Models.GitHubAppInstallation", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("id");

                    b.Property<long>("AccountId")
                        .HasColumnType("bigint")
                        .HasColumnName("account_id");

                    b.Property<string>("AccountLogin")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("account_login");

                    b.Property<string>("AccountType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("account_type");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTimeOffset?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at_utc");

                    b.Property<DateTimeOffset?>("DisabledAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("disabled_at_utc");

                    b.Property<long>("InstallationId")
                        .HasColumnType("bigint")
                        .HasColumnName("installation_id");

                    b.Property<DateTimeOffset>("InstalledAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("installed_at_utc");

                    b.Property<string>("OrganizationId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("organization_id");

                    b.Property<string>("RawInstallationJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("raw_installation_json");

                    b.Property<string>("RepositorySelection")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("repository_selection");

                    b.Property<DateTimeOffset?>("SuspendedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("suspended_at_utc");

                    b.Property<string>("TeamId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("team_id");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_code_review_github_app_installations");

                    b.HasIndex("InstallationId")
                        .IsUnique()
                        .HasDatabaseName("ix_code_review_github_app_installations_installation_id");

                    b.HasIndex("AccountLogin", "AccountType")
                        .HasDatabaseName("ix_code_review_github_app_installations_account_login_account_");

                    b.HasIndex("OrganizationId", "TeamId", "DisabledAtUtc")
                        .HasDatabaseName("ix_code_review_github_app_installations_organization_id_team_i");

                    b.ToTable("code_review_github_app_installations", "zeeq");
                });

            modelBuilder.Entity("Zeeq.Core.Models.GitHubCommentDesiredState", b =>
                {
                    b.Property<string>("OrganizationId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("organization_id");

                    b.Property<string>("RepositoryId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("repository_id");

                    b.Property<int>("PullRequestNumber")
                        .HasColumnType("integer")
                        .HasColumnName("pull_request_number");

                    b.Property<string>("CommandKind")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("command_kind");

                    b.Property<string>("CommandPayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("command_payload_json");

                    b.Property<long?>("GitHubIssueCommentId")
                        .HasColumnType("bigint")
                        .HasColumnName("git_hub_issue_comment_id");

                    b.Property<string>("OwnerQualifiedRepoName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("owner_qualified_repo_name");

                    b.Property<string>("TeamId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("team_id");

                    b.Property<string>("TraceContextJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("trace_context_json");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<long>("Version")
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("OrganizationId", "RepositoryId", "PullRequestNumber")
                        .HasName("pk_code_review_github_comment_desired_states");

                    b.HasIndex("OrganizationId", "UpdatedAtUtc")
                        .HasDatabaseName("ix_code_review_github_comment_desired_states_organization_id_u");

                    b.ToTable("code_review_github_comment_desired_states", "zeeq");
                });

            modelBuilder.Entity("Zeeq.Core.Models.GitHubWebhookDelivery", b =>
                {
                    b.Property<string>("DeliveryId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("delivery_id");

                    b.Property<string>("Action")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("action");

                    b.Property<string>("EventName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("event_name");

                    b.Property<string>("FailureMessage")
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)")
                        .HasColumnName("failure_message");

                    b.Property<string>("OrganizationId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("organization_id");

                    b.Property<DateTimeOffset?>("ProcessedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at_utc");

                    b.Property<DateTimeOffset>("ReceivedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at_utc");

                    b.Property<string>("RepositoryId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("repository_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<string>("TeamId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("team_id");

                    b.HasKey("DeliveryId")
                        .HasName("pk_code_review_github_webhook_deliveries");

                    b.HasIndex("OrganizationId", "ReceivedAtUtc")
                        .HasDatabaseName("ix_code_review_github_webhook_deliveries_organization_id_recei");

                    b.ToTable("code_review_github_webhook_deliveries", "zeeq");
                });

            modelBuilder.Entity("Zeeq.Core.Models.Organization", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("created_by_user_id");

                    b.Property<DateTimeOffset?>("DisabledAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("disabled_at_utc");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<string>("IconUrl")
                        .HasMaxLength(87380)
                        .HasColumnType("character varying(87380)")
                        .HasColumnName("icon_url");

                    b.Property<string>("Slug")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("slug");

                    b.Property<string>("Tier")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValue("Default")
                        .HasColumnName("tier");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_core_organizations");

                    b.HasIndex("CreatedByUserId")
                        .HasDatabaseName("ix_core_organizations_created_by_user_id");

                    b.HasIndex("DisabledAtUtc")
                        .HasDatabaseName("ix_core_organizations_disabled_at_utc");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_core_organizations_slug");

                    b.ToTable("core_organizations", "zeeq");
                });

            modelBuilder.Entity("Zeeq.Core.Models.OrganizationMembership", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("created_by_user_id");

                    b.Property<DateTimeOffset?>("DisabledAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("disabled_at_utc");

                    b.Property<DateTimeOffset?>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at_utc");

                    b.Property<string>("InvitedEmail")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("invited_email");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean")
                        .HasColumnName("is_default");

                    b.Property<string>("OrganizationId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("organization_id");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("role");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<string>("UserId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_core_organization_memberships");

                    b.HasIndex("CreatedByUserId")
                        .HasDatabaseName("ix_core_organization_memberships_created_by_user_id");

                    b.HasIndex("DisabledAtUtc")
                        .HasDatabaseName("ix_core_organization_memberships_disabled_at_utc");

                    b.HasIndex("InvitedEmail", "Status")
                        .HasDatabaseName("ix_core_organization_memberships_invited_email_status");

                    b.HasIndex("OrganizationId", "Status")
                        .HasDatabaseName("ix_core_organization_memberships_organization_id_status");

                    b.HasIndex("OrganizationId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_core_organization_memberships_organization_id_user_id")
                        .HasFilter("user_id IS NOT NULL AND status = 'Active'");

                    b.HasIndex("UserId", "IsDefault")
                        .HasDatabaseName("ix_core_organization_memberships_user_id_is_default");

                    b.HasIndex("UserId", "Status")
                        .HasDatabaseName("ix_core_organization_memberships_user_id_status");

                    b.ToTable("core_organization_memberships", "zeeq");
                });

            modelBuilder.Entity("Zeeq.Core.Models.Partition", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTimeOffset?>("DisabledAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("disabled_at_utc");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<string>("OrganizationId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("organization_id");

                    b.Property<string>("ScopeType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("scope_type");

                    b.Property<string>("TeamId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("team_id");

                    b.HasKey("Id")
                        .HasName("pk_core_partitions");

                    b.HasIndex("DisabledAtUtc")
                        .HasDatabaseName("ix_core_partitions_disabled_at_utc");

                    b.HasIndex("OrganizationId", "TeamId")
                        .HasDatabaseName("ix_core_partitions_organization_id_team_id");

                    b.HasIndex("ScopeType", "OrganizationId", "TeamId")
                        .HasDatabaseName("ix_core_partitions_scope_type_organization_id_team_id");

                    b.ToTable("core_partitions", "zeeq");
                });

            modelBuilder.Entity("Zeeq.Core.Models.PullRequestLookup", b =>
                {
                    b.Property<string>("OrganizationId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("organization_id");

                    b.Property<string>("RepositoryId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("repository_id");

                    b.Property<int>("PullRequestNumber")
                        .HasColumnType("integer")
                        .HasColumnName("pull_request_number");

                    b.Property<string>("OwnerQualifiedRepoName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("owner_qualified_repo_name");

                    b.Property<DateTimeOffset>("PullRequestCreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("pull_request_created_at_utc");

                    b.Property<string>("PullRequestRecordId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("pull_request_record_id");

                    b.Property<string>("TeamId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("team_id");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("OrganizationId", "RepositoryId", "PullRequestNumber")
                        .HasName("pk_code_review_pull_request_lookups");

                    b.HasIndex("PullRequestRecordId")
                        .IsUnique()
                        .HasDatabaseName("ix_code_review_pull_request_lookups_pull_request_record_id");

                    b.HasIndex("OrganizationId", "TeamId", "UpdatedAtUtc")
                        .HasDatabaseName("ix_code_review_pull_request_lookups_organization_id_team_id_up");

                    b.ToTable("code_review_pull_request_lookups", "zeeq");
                });

            modelBuilder.Entity("Zeeq.Core.Models.PullRequestRecord", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("AuthorLogin")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("author_login");

                    b.Property<string>("BaseBranch")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("base_branch");

                    b.Property<string>("Branch")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("branch");

                    b.Property<string>("ClaimStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("claim_status");

                    b.Property<string>("ClaimedByUserId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("claimed_by_user_id");

                    b.Property<DateTimeOffset>("CreatedFromWebhookAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_from_webhook_at_utc");

                    b.Property<DateTimeOffset?>("DisabledAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("disabled_at_utc");

                    b.Property<string>("FeatureId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("feature_id");

                    b.Property<string>("GitHubNodeId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("git_hub_node_id");

                    b.Property<string>("HeadSha")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("head_sha");

                    b.Property<string>("HtmlUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("html_url");

                    b.Property<bool>("IsDraft")
                        .HasColumnType("boolean")
                        .HasColumnName("is_draft");

                    b.Property<string>("LabelsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("labels_json");

                    b.Property<DateTimeOffset>("LastWebhookAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_webhook_at_utc");

                    b.Property<string>("OrganizationId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("organization_id");

                    b.Property<string>("OwnerQualifiedRepoName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("owner_qualified_repo_name");

                    b.Property<int>("PullRequestNumber")
                        .HasColumnType("integer")
                        .HasColumnName("pull_request_number");

                    b.Property<string>("RepositoryId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("repository_id");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("state");

                    b.Property<string>("TagsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("tags_json");

                    b.Property<string>("TeamId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("team_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id", "CreatedAtUtc")
                        .HasName("pk_code_review_pull_request_records");

                    b.HasIndex("RepositoryId", "PullRequestNumber", "CreatedAtUtc")
                        .HasDatabaseName("ix_code_review_pull_request_records_repository_id_pull_request");

                    b.HasIndex("OrganizationId", "ClaimStatus", "CreatedAtUtc", "Id")
                        .HasDatabaseName("ix_code_review_pull_request_records_organization_id_claim_stat");

                    b.HasIndex("OrganizationId", "TeamId", "CreatedAtUtc", "Id")
                        .HasDatabaseName("ix_code_review_pull_request_records_organization_id_team_id_cr");

                    b.ToTable("code_review_pull_request_records", "zeeq");
                });

            modelBuilder.Entity("Zeeq.Core.Models.Team", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("created_by_user_id");

                    b.Property<DateTimeOffset?>("DisabledAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("disabled_at_utc");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<bool>("IsRootTeam")
                        .HasColumnType("boolean")
                        .HasColumnName("is_root_team");

                    b.Property<string>("OrganizationId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("organization_id");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_core_teams");

                    b.HasAlternateKey("OrganizationId", "Id")
                        .HasName("ak_teams_organization_id_id");

                    b.HasIndex("CreatedByUserId")
                        .HasDatabaseName("ix_core_teams_created_by_user_id");

                    b.HasIndex("DisabledAtUtc")
                        .HasDatabaseName("ix_core_teams_disabled_at_utc");

                    b.ToTable("core_teams", "zeeq");
                });

            modelBuilder.Entity("Zeeq.Core.Models.TeamMembership", b =>
                {
                    b.Property<string>("OrganizationId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("organization_id");

                    b.Property<string>("TeamId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("team_id");

                    b.Property<string>("UserId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("user_id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("created_by_user_id");

                    b.Property<DateTimeOffset?>("DisabledAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("disabled_at_utc");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("role");

                    b.HasKey("OrganizationId", "TeamId", "UserId")
                        .HasName("pk_core_team_memberships");

                    b.HasIndex("CreatedByUserId")
                        .HasDatabaseName("ix_core_team_memberships_created_by_user_id");

                    b.HasIndex("UserId", "OrganizationId")
                        .HasDatabaseName("ix_core_team_memberships_user_id_organization_id");

                    b.HasIndex("OrganizationId", "TeamId", "DisabledAtUtc")
                        .HasDatabaseName("ix_core_team_memberships_organization_id_team_id_disabled_at_u");

                    b.ToTable("core_team_memberships", "zeeq");
                });

            modelBuilder.Entity("Zeeq.Core.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTimeOffset?>("DisabledAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("disabled_at_utc");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailVerified")
                        .HasColumnType("boolean")
                        .HasColumnName("email_verified");

                    b.Property<DateTimeOffset?>("LastLoginAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at_utc");

                    b.Property<string>("PictureUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("picture_url");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_core_users");

                    b.HasIndex("DisabledAtUtc")
                        .HasDatabaseName("ix_core_users_disabled_at_utc");

                    b.HasIndex("Email")
                        .HasDatabaseName("ix_core_users_email");

                    b.ToTable("core_users", "zeeq");
                });

            modelBuilder.Entity("Zeeq.Core.Models.UserToken", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at_utc");

                    b.Property<DateTimeOffset?>("LastUsedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_used_at_utc");

                    b.Property<string>("OrganizationId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("organization_id");

                    b.Property<string>("OwnerProvider")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("owner_provider");

                    b.Property<string>("OwnerProviderSubject")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("owner_provider_subject");

                    b.Property<string>("OwnerUserId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("owner_user_id");

                    b.Property<DateTimeOffset?>("RevokedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at_utc");

                    b.Property<string>("SelectedPartitionIdsJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("selected_partition_ids_json");

                    b.Property<string>("TeamId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("team_id");

                    b.HasKey("Id")
                        .HasName("pk_auth_user_tokens");

                    b.HasIndex("OwnerUserId")
                        .HasDatabaseName("ix_auth_user_tokens_owner_user_id");

                    b.HasIndex("OrganizationId", "TeamId", "OwnerUserId")
                        .HasDatabaseName("ix_auth_user_tokens_organization_id_team_id_owner_user_id");

                    b.ToTable("auth_user_tokens", "zeeq");
                });

            modelBuilder.Entity("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreApplication", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("ApplicationType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("application_type");

                    b.Property<string>("ClientId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("client_id");

                    b.Property<string>("ClientSecret")
                        .HasColumnType("text")
                        .HasColumnName("client_secret");

                    b.Property<string>("ClientType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("client_type");

                    b.Property<string>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("concurrency_token");

                    b.Property<string>("ConsentType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("consent_type");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("DisplayNames")
                        .HasColumnType("text")
                        .HasColumnName("display_names");

                    b.Property<string>("JsonWebKeySet")
                        .HasColumnType("text")
                        .HasColumnName("json_web_key_set");

                    b.Property<string>("Permissions")
                        .HasColumnType("text")
                        .HasColumnName("permissions");

                    b.Property<string>("PostLogoutRedirectUris")
                        .HasColumnType("text")
                        .HasColumnName("post_logout_redirect_uris");

                    b.Property<string>("Properties")
                        .HasColumnType("text")
                        .HasColumnName("properties");

                    b.Property<string>("RedirectUris")
                        .HasColumnType("text")
                        .HasColumnName("redirect_uris");

                    b.Property<string>("Requirements")
                        .HasColumnType("text")
                        .HasColumnName("requirements");

                    b.Property<string>("Settings")
                        .HasColumnType("text")
                        .HasColumnName("settings");

                    b.HasKey("Id")
                        .HasName("pk_open_iddict_applications");

                    b.HasIndex("ClientId")
                        .IsUnique()
                        .HasDatabaseName("ix_open_iddict_applications_client_id");

                    b.ToTable("OpenIddictApplications", "zeeq");
                });

            modelBuilder.Entity("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreAuthorization", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("ApplicationId")
                        .HasColumnType("text")
                        .HasColumnName("application_id");

                    b.Property<string>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("concurrency_token");

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creation_date");

                    b.Property<string>("Properties")
                        .HasColumnType("text")
                        .HasColumnName("properties");

                    b.Property<string>("Scopes")
                        .HasColumnType("text")
                        .HasColumnName("scopes");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<string>("Subject")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasColumnName("subject");

                    b.Property<string>("Type")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_open_iddict_authorizations");

                    b.HasIndex("ApplicationId", "Status", "Subject", "Type")
                        .HasDatabaseName("ix_open_iddict_authorizations_application_id_status_subject_type");

                    b.ToTable("OpenIddictAuthorizations", "zeeq");
                });

            modelBuilder.Entity("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreScope", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("concurrency_token");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Descriptions")
                        .HasColumnType("text")
                        .HasColumnName("descriptions");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("DisplayNames")
                        .HasColumnType("text")
                        .HasColumnName("display_names");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Properties")
                        .HasColumnType("text")
                        .HasColumnName("properties");

                    b.Property<string>("Resources")
                        .HasColumnType("text")
                        .HasColumnName("resources");

                    b.HasKey("Id")
                        .HasName("pk_open_iddict_scopes");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_open_iddict_scopes_name");

                    b.ToTable("OpenIddictScopes", "zeeq");
                });

            modelBuilder.Entity("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreToken", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("ApplicationId")
                        .HasColumnType("text")
                        .HasColumnName("application_id");

                    b.Property<string>("AuthorizationId")
                        .HasColumnType("text")
                        .HasColumnName("authorization_id");

                    b.Property<string>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("concurrency_token");

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creation_date");

                    b.Property<DateTime?>("ExpirationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expiration_date");

                    b.Property<string>("Payload")
                        .HasColumnType("text")
                        .HasColumnName("payload");

                    b.Property<string>("Properties")
                        .HasColumnType("text")
                        .HasColumnName("properties");

                    b.Property<DateTime?>("RedemptionDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("redemption_date");

                    b.Property<string>("ReferenceId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("reference_id");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<string>("Subject")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasColumnName("subject");

                    b.Property<string>("Type")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_open_iddict_tokens");

                    b.HasIndex("AuthorizationId")
                        .HasDatabaseName("ix_open_iddict_tokens_authorization_id");

                    b.HasIndex("ReferenceId")
                        .IsUnique()
                        .HasDatabaseName("ix_open_iddict_tokens_reference_id");

                    b.HasIndex("ApplicationId", "Status", "Subject", "Type")
                        .HasDatabaseName("ix_open_iddict_tokens_application_id_status_subject_type");

                    b.ToTable("OpenIddictTokens", "zeeq");
                });

            modelBuilder.Entity("Zeeq.Core.Models.ClientCredential", b =>
                {
                    b.HasOne("Zeeq.Core.Models.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_auth_client_credentials_organizations_organization_id");

                    b.HasOne("Zeeq.Core.Models.User", null)
                        .WithMany()
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_auth_client_credentials_users_owner_user_id");

                    b.HasOne("Zeeq.Core.Models.Team", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "TeamId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_auth_client_credentials_teams_organization_id_team_id");
                });

            modelBuilder.Entity("Zeeq.Core.Models.CodeRepository", b =>
                {
                    b.HasOne("Zeeq.Core.Models.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_code_review_repositories_organizations_organization_id");

                    b.HasOne("Zeeq.Core.Models.Team", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "TeamId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_code_review_repositories_teams_organization_id_team_id");
                });

            modelBuilder.Entity("Zeeq.Core.Models.DcrClientSetup", b =>
                {
                    b.HasOne("Zeeq.Core.Models.User", null)
                        .WithMany()
                        .HasForeignKey("ClaimedUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_auth_dcr_client_setups_users_claimed_user_id");

                    b.HasOne("Zeeq.Core.Models.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_auth_dcr_client_setups_organizations_organization_id");

                    b.HasOne("Zeeq.Core.Models.Team", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "TeamId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_auth_dcr_client_setups_teams_organization_id_team_id");
                });

            modelBuilder.Entity("Zeeq.Core.Models.ExternalUserIdentity", b =>
                {
                    b.HasOne("Zeeq.Core.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_auth_user_identities_users_user_id");
                });

            modelBuilder.Entity("Zeeq.Core.Models.GitHubAppInstallation", b =>
                {
                    b.HasOne("Zeeq.Core.Models.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_code_review_github_app_installations_organizations_organiza");

                    b.HasOne("Zeeq.Core.Models.Team", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "TeamId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_code_review_github_app_installations_teams_organization_id_");
                });

            modelBuilder.Entity("Zeeq.Core.Models.Organization", b =>
                {
                    b.HasOne("Zeeq.Core.Models.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_core_organizations_users_created_by_user_id");
                });

            modelBuilder.Entity("Zeeq.Core.Models.OrganizationMembership", b =>
                {
                    b.HasOne("Zeeq.Core.Models.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_core_organization_memberships_users_created_by_user_id");

                    b.HasOne("Zeeq.Core.Models.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_core_organization_memberships_core_organizations_organizati");

                    b.HasOne("Zeeq.Core.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_core_organization_memberships_users_user_id");
                });

            modelBuilder.Entity("Zeeq.Core.Models.Partition", b =>
                {
                    b.HasOne("Zeeq.Core.Models.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_core_partitions_core_organizations_organization_id");

                    b.HasOne("Zeeq.Core.Models.Team", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "TeamId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_core_partitions_teams_organization_id_team_id");
                });

            modelBuilder.Entity("Zeeq.Core.Models.PullRequestRecord", b =>
                {
                    b.HasOne("Zeeq.Core.Models.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_code_review_pull_request_records_core_organizations_organiz");

                    b.HasOne("Zeeq.Core.Models.CodeRepository", null)
                        .WithMany()
                        .HasForeignKey("RepositoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_code_review_pull_request_records_code_review_repositories_r");
                });

            modelBuilder.Entity("Zeeq.Core.Models.Team", b =>
                {
                    b.HasOne("Zeeq.Core.Models.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_core_teams_users_created_by_user_id");

                    b.HasOne("Zeeq.Core.Models.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_core_teams_core_organizations_organization_id");
                });

            modelBuilder.Entity("Zeeq.Core.Models.TeamMembership", b =>
                {
                    b.HasOne("Zeeq.Core.Models.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_core_team_memberships_users_created_by_user_id");

                    b.HasOne("Zeeq.Core.Models.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_core_team_memberships_core_organizations_organization_id");

                    b.HasOne("Zeeq.Core.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_core_team_memberships_users_user_id");

                    b.HasOne("Zeeq.Core.Models.Team", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "TeamId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_core_team_memberships_core_teams_organization_id_team_id");
                });

            modelBuilder.Entity("Zeeq.Core.Models.UserToken", b =>
                {
                    b.HasOne("Zeeq.Core.Models.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_auth_user_tokens_core_organizations_organization_id");

                    b.HasOne("Zeeq.Core.Models.User", null)
                        .WithMany()
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_auth_user_tokens_core_users_owner_user_id");

                    b.HasOne("Zeeq.Core.Models.Team", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "TeamId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_auth_user_tokens_core_teams_organization_id_team_id");
                });

            modelBuilder.Entity("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreAuthorization", b =>
                {
                    b.HasOne("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreApplication", "Application")
                        .WithMany("Authorizations")
                        .HasForeignKey("ApplicationId")
                        .HasConstraintName("fk_open_iddict_authorizations_open_iddict_applications_application");

                    b.Navigation("Application");
                });

            modelBuilder.Entity("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreToken", b =>
                {
                    b.HasOne("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreApplication", "Application")
                        .WithMany("Tokens")
                        .HasForeignKey("ApplicationId")
                        .HasConstraintName("fk_open_iddict_tokens_open_iddict_applications_application_id");

                    b.HasOne("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreAuthorization", "Authorization")
                        .WithMany("Tokens")
                        .HasForeignKey("AuthorizationId")
                        .HasConstraintName("fk_open_iddict_tokens_open_iddict_authorizations_authorization_id");

                    b.Navigation("Application");

                    b.Navigation("Authorization");
                });

            modelBuilder.Entity("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreApplication", b =>
                {
                    b.Navigation("Authorizations");

                    b.Navigation("Tokens");
                });

            modelBuilder.Entity("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreAuthorization", b =>
                {
                    b.Navigation("Tokens");
                });
#pragma warning restore 612, 618
        }
    }
}
