[tools]
cloud-sql-proxy = "latest"
"dotnet:CSharpRepl" = "0.9.2"
node = "26"
aspire = "13.4.6"

[env]
CLOUDSDK_CONFIG = "{{config_root}}/.config/.gcloud-config"
OPENCODE_CONFIG = "{{config_root}}/.config/opencode.json"
GCP_PROJECT_ID = "zeeq-ai-prod"
GCP_RUNTIME_SA = "zeeq-app-svc@zeeq-ai-prod.iam.gserviceaccount.com"
CSQL_PROXY_INSTANCE_CONNECTION_NAME = "zeeq-ai-prod:us-central1:zeeq-pg-prod"
PUBSUB_PROJECT_ID = "zeeq-dev-local"
