<template>
  <div class="flex flex-col gap-4 pt-2">
    <!-- Notion webhook setup state: backend owns URL construction and token decrypt. -->
    <UAlert
      color="info"
      variant="subtle"
      title="Configure this callback URL in Notion"
      description="Paste the callback URL into your Notion integration webhook settings. After Notion sends the verification challenge, copy the captured verification token back to Notion."
    />

    <div class="rounded-md border border-default p-3 text-sm">
      <div class="flex items-center justify-between gap-2">
        <span class="font-semibold">Webhook status</span>
        <UBadge
          :label="webhookStatusLabel"
          :color="webhookStatusColor"
          size="sm"
          variant="subtle"
        />
      </div>

      <div class="mt-2 flex flex-col gap-1 text-xs text-muted">
        <div v-if="source?.webhookActivatedAtUtc">
          Activated: {{ formatDate(source.webhookActivatedAtUtc) }}
        </div>
        <div v-else-if="state?.webhookActivatedAtUtc">
          Activated: {{ formatDate(state.webhookActivatedAtUtc) }}
        </div>
        <div v-if="state?.webhookSubscriptionId">
          Subscription: {{ state.webhookSubscriptionId }}
        </div>
        <div v-if="state">
          Callback generation: {{ state.callbackTokenSerial }}
        </div>
      </div>
    </div>

    <div
      v-if="loading && !state"
      class="flex items-center gap-2 text-sm text-muted"
    >
      <UIcon name="i-hugeicons-loading-03" class="size-4 animate-spin" />
      Loading webhook setup…
    </div>

    <template v-else-if="state">
      <UFormField
        label="Callback URL"
        description="Use the exact URL generated by Zeeq; it includes a revocable callback token."
      >
        <UInput
          :model-value="state.callbackUrl"
          readonly
          class="w-full font-mono text-xs"
        >
          <template #trailing>
            <UButton
              icon="i-hugeicons-copy-01"
              color="neutral"
              variant="ghost"
              size="xs"
              aria-label="Copy callback URL"
              @click="emits('copy', state.callbackUrl)"
            />
          </template>
        </UInput>
      </UFormField>

      <UFormField
        label="Verification token"
        :description="verificationDescription"
      >
        <UInput
          :model-value="state.verificationToken ?? ''"
          :placeholder="
            state.verificationTokenAvailable
              ? 'Token unavailable'
              : 'Waiting for Notion challenge'
          "
          readonly
          class="w-full font-mono text-xs"
        >
          <template #trailing>
            <UButton
              icon="i-hugeicons-copy-01"
              color="neutral"
              variant="ghost"
              size="xs"
              aria-label="Copy verification token"
              :disabled="!state.verificationToken"
              @click="
                state.verificationToken
                  ? emits('copy', state.verificationToken)
                  : undefined
              "
            />
          </template>
        </UInput>
      </UFormField>
    </template>

    <UAlert
      v-else
      color="warning"
      variant="subtle"
      title="Webhook setup unavailable"
      description="Refresh the setup state. If this continues, the library may not be a Notion-backed library."
    />

    <div class="flex flex-wrap justify-end gap-2">
      <UButton
        label="Refresh"
        icon="i-hugeicons-refresh"
        color="neutral"
        variant="ghost"
        :loading="loading"
        @click="emits('refresh')"
      />
      <UButton
        label="Run full resync"
        icon="i-hugeicons-refresh"
        color="neutral"
        variant="subtle"
        :loading="fullResyncing"
        :disabled="fullResyncing || sourceInFlight"
        @click="emits('full-resync')"
      />
      <ZeeqPopConfirm
        title="Reset Notion webhook"
        body="Resetting invalidates the current callback URL generation and clears captured verification state. You will need to re-run Notion webhook verification."
        label="Reset webhook"
        icon="i-hugeicons-clean"
        color="warning"
        variant="subtle"
        confirm-label="Reset"
        confirm-color="neutral"
        confirm-icon="i-hugeicons-clean"
        :loading="resetting"
        :disabled="resetting"
        @confirm="emits('reset')"
      />
    </div>
  </div>
</template>

<script setup lang="ts">
import type { LibrarySourceResponse } from "@/api/generated/types/LibrarySourceResponse";
import type { NotionWebhookStateResponse } from "@/api/generated/types/NotionWebhookStateResponse";
import ZeeqPopConfirm from "@/components/ZeeqPopConfirm.vue";

const props = defineProps<{
  state: NotionWebhookStateResponse | null;
  source: LibrarySourceResponse | null;
  loading: boolean;
  resetting: boolean;
  fullResyncing: boolean;
}>();

const emits = defineEmits<{
  refresh: [];
  reset: [];
  "full-resync": [];
  copy: [value: string];
}>();

const sourceInFlight = computed(
  () =>
    props.source?.syncStatus === "queued" ||
    props.source?.syncStatus === "running",
);

const webhookActivated = computed(
  () => props.state?.webhookActivated || props.source?.webhookActivated,
);

const webhookStatusLabel = computed(() =>
  webhookActivated.value ? "Activated" : "Not activated",
);

const webhookStatusColor = computed(() =>
  webhookActivated.value ? ("success" as const) : ("warning" as const),
);

const verificationDescription = computed(() =>
  props.state?.verificationToken
    ? "Paste this token into Notion to complete webhook verification."
    : "After Notion calls the callback URL, refresh this tab to show the captured token.",
);

function formatDate(value: Date | string) {
  const date = value instanceof Date ? value : new Date(value);
  return date.toLocaleString();
}
</script>
