namespace Zeeq.Core.Carts;

/// <summary>
/// An immutable saved collection of code-review findings a local agent can retrieve.
/// </summary>
/// <remarks>
/// <para>
/// <b>Lifecycle.</b> Draft carts live entirely in the browser (Pinia store +
/// VueUse <c>useStorage</c>) while the user builds them across PRs.  Rows only exist
/// here once the user clicks <b>Save cart</b> — that is the one write that persists
/// a cart server-side.  After save, the row is immutable: the only server-side mutations
/// are create (once) and delete.  To "edit" a saved cart, the user copies it to a new
/// local draft with a fresh id and generated name, edits that, and saves as a new cart.
/// </para>
/// <para>
/// <b>Dual-payload design.</b>  Every cart row stores two JSON arrays:
/// <see cref="ItemSummaries"/> (lightweight — hash, title, facet, summary, criticality,
/// annotation) for the startup list UI, and <see cref="ItemsPayload"/> (full body +
/// provenance) for the MCP tool, text compilation, and explicit copy-to-new-draft.
/// The browser loads <c>GET /carts</c> on startup, which returns only summaries — the
/// full payload is never fetched during normal application use.
/// </para>
/// <para>
/// <b>Retention.</b>  Stored in an unlogged Postgres table — carts are a workflow
/// convenience, not durable application data.  Loss on an unclean shutdown is acceptable.
/// A <c>pg_cron</c> job prunes rows older than seven days via <see cref="UpdatedAtUtc"/>.
/// </para>
/// <para>
/// <b>Client-generated id.</b>  <see cref="Id"/> is a human-memorable name
/// (adjective-noun-nanoid10, e.g. <c>snappy-lake-a1b2c3d4e5</c>) generated by
/// <c>generateCartName()</c> when the draft is first created in the browser and kept
/// stable across the local→saved transition.  This means the cart id is known before
/// the server ever sees the cart, which is unusual — see <see cref="ICartStore.CreateAsync"/>
/// for the unique-violation guard that makes it safe.
/// </para>
/// </remarks>
public sealed class Cart
{
    /// <summary>
    /// Stable cart identifier, minted client-side when the draft was first created and
    /// preserved after save. This is the value a user copies into agent instructions.
    /// </summary>
    public string Id { get; init; } = null!;

    /// <summary>Organization that owns the cart.</summary>
    public string OrganizationId { get; init; } = null!;

    /// <summary>Optional team the owner was active in when the cart was first saved.</summary>
    public string? TeamId { get; init; }

    /// <summary>Local user id (OpenIddict <c>sub</c>) that owns the cart.</summary>
    public string OwnerUserId { get; init; } = null!;

    /// <summary>
    /// Human-memorable generated name (adjective-noun-nanoid10), minted client-side at
    /// draft creation and immutable thereafter. See the frontend name generator.
    /// </summary>
    public string Name { get; init; } = null!;

    /// <summary>
    /// Lightweight summary of every finding, in add-order.  Used by <c>GET /carts</c>
    /// (the startup list endpoint) and saved-cart display in the slideover.
    /// Intentionally excludes the full finding body — see <see cref="ItemsPayload"/>
    /// for the full snapshot.
    /// </summary>
    /// <remarks>
    /// <see cref="List{T}"/> backing — not <c>init</c>-only — so EF Core <c>OwnsMany</c>
    /// can populate the collection during materialization.  The public type is
    /// <see cref="IReadOnlyList{T}"/>; only the store layer touches the concrete type.
    /// </remarks>
    public IReadOnlyList<CartFindingSummary> ItemSummaries { get; set; } =
        new List<CartFindingSummary>();

    /// <summary>
    /// Full finding snapshots, including body payload, used for copy-to-draft and MCP/text compilation.
    /// </summary>
    /// <remarks>
    /// Backed by a mutable <see cref="List{T}"/> so EF Core <c>OwnsMany</c> can populate
    /// the collection during materialization.
    /// </remarks>
    public IReadOnlyList<CartFindingSnapshot> ItemsPayload { get; set; } =
        new List<CartFindingSnapshot>();

    /// <summary>
    /// When the draft was originally created client-side (from the draft's own
    /// <c>createdAtUtc</c>, sent through unchanged on first save) — shown in the UI as "the
    /// date" for this cart.
    /// </summary>
    public DateTimeOffset CreatedAtUtc { get; init; }

    /// <summary>When the initial save request that persisted this row was processed.</summary>
    public DateTimeOffset SavedAtUtc { get; init; }

    /// <summary>
    /// Equal to <see cref="SavedAtUtc"/> for immutable saved carts.  Exists only for
    /// ordering (newest-saved-first in the slideover) and so the seven-day <c>pg_cron</c>
    /// retention job has a single column to evaluate.
    /// </summary>
    public DateTimeOffset UpdatedAtUtc { get; init; }
}
